# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'HomeAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for HomeAssignment
  pod 'SnapKit', '~> 5.7.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  
  target 'HomeAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'HomeAssignmentUITests' do
    # Pods for testing
  end
  
end
